# OpenAPIs endpoint
quarkus.rest-client."supplier_yaml".url=http://order-swf-tut-svc.swf-shared
quarkus.rest-client."inventory_yaml".url=http://order-swf-tut-svc.swf-shared
# quarkus.rest-client."supplier_yaml".url=http://localhost:8090
# quarkus.rest-client."inventory_yaml".url=http://localhost:8090

quarkus.dev-ui.cors.enabled=false
